### ISSUE TITLE
Ddoc Lab feature: import source document

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#13]
The import feature to read any ddoc into Ddoc Lab is great for migrating to Ddoc Lab from e.g. Couchapp.
Once Ddoc Lab has been deployed to several sites maintained by several team members, it would be very convenient to import a Ddoc Lab source document in a similar way (and remove another reason go Futon/Fauxton).
UI-wise it could be part of the dialogue that allow template selection after clicking right-side [+] button

**Comment by ermouth** [comment]
Feature is in place, closing.
