### ISSUE TITLE
Inliner feature: Drag and drop to reorder sections

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#14]
Inliner is in its basic concept a intuitive, cut&paste writing app for Word-user.
Where is departs from the normal wysiwyg html app is when you are allowed to insert images, videos, apps into the text and the html section is then split into sections that are kept separate in the JSON document with metadata for a site to deliver through a totally different look with adaptive design.

The content creator relates to a generic UI that is suitable for composing a document with a given structure. This can later be overridden by the site using his/her content. The content can go into a workflow where the original writer retains the privilege to update the content, correct a type etc, while the content is live on one or more sites.

A conflict of priorities arises when it comes to rearranging sections. Ideally, the user should be able to drag and drop sections to rearrange sections. But to support the generic "inline" feeling of writing an article this is not easy to do. Float layout for images, text an other elements provide the writer with a look that keeps the focus on the flow of content, what is the main picture, should this picture be tiny and to the riight or should, it this first video going to be wide with several small ones beneith, etc.
The writer is allowed to compose the page with an "inline" feeling.

Therefore D&D reorder needs to be a different mode.
Set top level CSS class to tile mode which enable the D&D function at the same time.

**Comment by ermouth** [comment]
Implemented using block copy/paste, so closing.
