### ISSUE TITLE
Differences between cloudwall.me and the github repository

### ISSUE THREAD

**Issue by ronycohen** [ermouth/cloudwall#18]
On the cloudwall.me it looks like the version is higer than the repo : 

I did : 

```
git clone git://github.com/ermouth/cloudwall.git cloudWall
```

Clouwall.me : 

![image](https://cloud.githubusercontent.com/assets/7273443/14893719/c87ee0cc-0d70-11e6-8504-227c1ca61347.png)

![image](https://cloud.githubusercontent.com/assets/7273443/14893790/0a8e5b14-0d71-11e6-9c83-185c74982bae.png)

Cloudwall repo : 

![image](https://cloud.githubusercontent.com/assets/7273443/14893772/f88efed2-0d70-11e6-91ac-48667386a9c0.png)

![image](https://cloud.githubusercontent.com/assets/7273443/14893798/142c8132-0d71-11e6-8a95-9e498cab7d39.png)

**Comment by ermouth** [comment]
Yes, I plan to publish 2.0 to github when it comes out of beta. 1.9 was skipped for several reasons, now only 1.8 is at github, sorry.

**Comment by ronycohen** [comment]
No worries :) 
Thank you for the share !
