### ISSUE TITLE
UI layout

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#2]
Since Cloudwall is an innovative concept with a very wide scope it would benefit greatly from having a more intuitive UI, and a good place to start is the Ddoc Lab, since is could set the standard for tools central to Cloudwall. I was confused at start by each project having a sync db address and then a single db sync to the right (the development environment db). Hierarchically, I go from level 2-3-1 instead of the usual 1-2-3.

It would be much easier to grasp, and consistent when switching into Cloudwall for running Ddoc Lab  if the database sync was kept to the left. Multiple DBs could be held in the modal panel represented by the cloud button.  The _D logo could be the expand/collapse toggle button.

The story: Cloud holds my DBs, I select one of them to get my Ddoc projects, once a project is selected I work on the app. All my DBs (work environments) are synced as I work, one might be in my local CouchDB another (at a lower frequency) is the environment I share with my team.

Having easy access to muliple databased inside Ddoc Lab makes it easy to switch between sites/clients or to fork my work for an experient that involve selveral Ddocs.

![1](https://cloud.githubusercontent.com/assets/48370/9024976/b209bea4-38ee-11e5-81b9-4983189a3460.jpg)
![2](https://cloud.githubusercontent.com/assets/48370/9024978/b87e367a-38ee-11e5-9aa6-4389d5e13e19.jpg)
This also gives a left-to-right of the hierarchy and could have been supported by a drops hadow or a different background color.
![3b](https://cloud.githubusercontent.com/assets/48370/9025023/b76ab4a0-38f0-11e5-94a2-4195201a992c.jpg)

![3](https://cloud.githubusercontent.com/assets/48370/9024980/c86f12c0-38ee-11e5-89fa-a8b2b42118b7.jpg)
![4](https://cloud.githubusercontent.com/assets/48370/9025040/c6bf6d32-38f1-11e5-8b8f-972d901e8692.jpg)

**Comment by ermouth** [comment]
I‘ve tested layout you offer. Chosing layout was a tradeoff between necessety keeping editor frame at the center of screen and clean hierarchy. Editor won. 

Once 2-3-1 hierarhy grasped, it does not annoy. Editor always shifted right does. Collapsing pane also does, especially when you have enough space.

**Comment by johs** [comment]
Agree on annoyance of collapsing panels that push center of attantion around. Fixed position is important. I also like centered when in fullscreen mode.

How about collapsing project list vertically?
(+ button and > symbol bring up project list, active project takes title position when collapsed)

Level 1 (future?): Switching between DBs is very rare and can take place in the modal panel (from a sync button)
Level 2: Switching between projects i rare enough to take place in the vertical collapsable
Level 3: UI when in a project could make use of right side for level 4. E.g. contextual help and a conversation like the support function of minutes.io, which I find a very elegant integration of help. In this case it could be team collaboration comments on the very component. Or other level 4 items.

Tradeoff avoided
More intuitive navigation scheme both top-down and left-right
![6](https://cloud.githubusercontent.com/assets/48370/9025864/d50da20c-3917-11e5-927b-957e4dfb4a4d.jpg)

![8](https://cloud.githubusercontent.com/assets/48370/9026051/b65b6674-3920-11e5-9e8d-b241410ee0ed.jpg)

"Site name" is environment that keeps the source code, so it could be and individual developer's collection of ddocs, or parts of those ddocs  ("Eric's components" or "CSS library") or it could be the database that holds an entire site ("XYZsite Source code"). The team collaboration functionality with the "superimposing" merge of the JSON tree is already awsome in Ddoc Lab, so the combination of "site name" and "project name" is important to keep in sight (like.. "Am I working on the official site or on my personal fork of this?").
The "site name" could therefore be seen as one of my many "ddoc labs", making the logo+sitename a natural unit. Conceptually, _D DB-name would make more sense to me than _D project-name as it is today.

**Comment by ermouth** [comment]
Help is scheduled to be written, but it won‘t be available in situ, only by link. Three reasons:
- it must have pictures – they may increase installation JSON dramatically if included;
- modern IDE generally have no help/docs in app frame, only online;
- help/docs pages at project site is a good channel for communicating with end users.

**Comment by johs** [comment]
Buy what you say about help.
My main point here is the hierarchy, to work better for a first-time intro and make it easier to understand that Ddoc is a collection of ddocs, your ddoc lab. You kan have several labs and each lab can hold ddocs that belong in any database.
Hierarcy: Your Lab > Ddoc projects > Resource

At present, you get to different labs by installing _D (Ddoc Lab) in a CouchDB database and running it from here. I will create a separate issue on multiple labs since is has little to do with the UI layout.
