### ISSUE TITLE
CW UI suggestion: Sectioning for better overall understanding

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#21]
CW is a fantastic tool where the unique super-power features are hard to read because there is little visual compartmentalization. I suggest some use of background color and shadow for this in addition to some other simplifications and rearrangements (se small separate issues). What I think this would improve is:
1. Easier to understand the 3 main parts cloud > total edit/test/deploy/manage-environment > work session slots
2. Easier to differntiate between the menus/lists of tools in CW and the loaded App.

Present version and suggestions:
<img width="963" alt="cw2-problems" src="https://cloud.githubusercontent.com/assets/48370/22395196/c1ac4b74-e536-11e6-9ce4-ef3078a9daf4.png">

Database loaded, left and right panes are "lowered" to indicate working area better and by highlighting show what data resource is active and where it belongs in the cloud(s):
<img width="963" alt="cw2" src="https://cloud.githubusercontent.com/assets/48370/22395201/e78e5f94-e536-11e6-90d1-9a7d10170c0a.png">

Top can be expanded to show System Apps without confusing these with the content of the active data base (system DB removed since the fact that the system is made by the system can be a mental meltdown for some)
<img width="963" alt="cw2-db" src="https://cloud.githubusercontent.com/assets/48370/22395212/0f2b328e-e537-11e6-8685-fb9e191a1f6a.png">

Tabs are used to switch between launcable apps and documents in the database:

<img width="963" alt="cw2-db-apps" src="https://cloud.githubusercontent.com/assets/48370/22395226/7f2cd1c8-e537-11e6-8d0a-dc95d8a1e7bb.png">

When an app is launched, the menues of this app is not confused with CW system menus. 
The tabs to left and right highlights where you are switching, e.g. in a case where you have loaded similar assets deployed to differnt servers and want to update/compare by switching back and forth, using the righthand session slots. 
  
<img width="963" alt="cw2-work" src="https://cloud.githubusercontent.com/assets/48370/22395240/afaeac36-e537-11e6-8c8c-3482eece4c70.png">

In this last case, the benefit is more visible as the present version would present a lot of controls and menues that make it easy to get lost, since the IDE is to all-encompassing and powerfull with multiple ways of editing both data and apps.  
<img width="955" alt="screen shot 2017-01-28 at 09 06 57 copy" src="https://cloud.githubusercontent.com/assets/48370/22395291/46265122-e539-11e6-89c1-27f18245cae3.png">

**Comment by ermouth** [comment]
Running apps have different width, here width is bound to screen size. Irrelevant.
