### ISSUE TITLE
Other js Libraries add HOWTO

### ISSUE THREAD

**Issue by BillMeyerRSA** [ermouth/cloudwall#23]
If I want to add e.g. Chartjs to cloudwall, how would I go about doing that?
Cloudwall looks incredible btw.

**Comment by ermouth** [comment]
You should attach `chart.js` script as `lib/chart.js` to CloudWall design document, if you run Cloudwall from CouchDB. If you do standalone, place the script in `lib/` at you hosting.

When creating an app, add section `require:[{'window.Chart':'lib/chart.js'}]` to app JSON. Your app will load chart.js onbefore it starts, or will fail to run if script is not available for some reason.

If `window.Chart` is already present when app starts, then no script requested: conditional assumed already fulfilled.

**Comment by ermouth** [comment]
Here is the manual on require: https://cloudwall.me/api/jquerymy#h-16hwn9zz

**Comment by BillMeyerRSA** [comment]
Thanks for the prompt response
Will give it a try.

**Comment by BillMeyerRSA** [comment]
Just for convenience for someone else trying it. 
Remember to add path when uploading
![cwselectdesigndoc](https://user-images.githubusercontent.com/38781014/64868598-f7315580-d63f-11e9-96f0-8d0f36b98d02.png)
![cwnamefilewithpath](https://user-images.githubusercontent.com/38781014/64868613-fb5d7300-d63f-11e9-9e98-7f5ceb484a88.png)
