### ISSUE TITLE
.png in Add Image

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#3]
Add Image in Ddoc Lab seems to convert to jpg.
I can change the extension to png (at upload) and property to image/png, but I guess that is not  a viable workaround for uploading png?

**Comment by ermouth** [comment]
Just attach png as a file.

**Comment by ermouth** [comment]
Added ability to set output format and quality (for jpeg) to my plans. Although first experiments showed, that resampling pngs with transparency is not the best way to deal with them. Edge sharpness significantly degrades during resample.

**Comment by johs** [comment]
Love the image cropper, but guess this makes sense in the way that whenever a user crops something it is OK to convert it to jpg, e.g. a screen dump. Whenever you really want the non-jpg quality you make files as they should be in the first place, e.g. icons in png or svg or animations in gif.
Good with this, closed for me.

**Comment by ermouth** [comment]
In fact having svg editor onboard doesn‘t look impossible. http://svg-edit.googlecode.com/svn/branches/stable/editor/svg-editor.html

I‘m going to review its code to examine can it be smoothly embedded in CloudWall. It can have value not only in Ddoc Lab.

**Comment by johs** [comment]
This issue, is taken care of beyond expectations and is closed for me
Comments for other issues
- jpg named as png is not detected and vice versa
- would have preferred separate buttons for crop and upload to have a second-guess crop
- svg edit could be great
