### ISSUE TITLE
Multiple "labs" in Ddoc Lab

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#4]
in Ddoc Lab at present, you get to different collections of ddoc projects by installing _D (Ddoc Lab) in a CouchDB database and running it from here. Could the modal panel for setting up sync have functionality that allowed you to set up several databases as "environments" that you switch between?

The ida being that your _D (the instance of Ddoc Lab) holds several "labs" (environments) that each have a collection of ddoc projects that are set up to be published to various databases that have nothing to do with where the "labs" containing the source code of the ddocs are.

A use case would be a developer that want to switch between two version of a site containing several interdependent docs.

**Comment by ermouth** [comment]
Why I should not do it in CloudWall mini:
- I can‘t ensure, that Ddoc Lab version is identical in different DBs – so I need to load own app for each DB
- I need to hold several DB connections (and, though, replications) – and define all mechanics how they replicate
- I need to create special interfaces that provide DB switching, adding them to the list, managing this list and so on.

If I do all above, I re-create big CloudWall. But it already exist with all these features.

**Comment by johs** [comment]
OK:)

**Comment by johs** [comment]
I have not used offline a lot, but I think I get it now..
Ddoc Lab in a source db reserves a workspace for that domain in local store, so having an instance of Ddoc Lab in each project makes a lot of sence. Domain + sourceDB = Lab. Browser can hold several labs in localstore, but requires a separate instance for the lab software (Ddoc Lab) to stay this simple. And that is good. This concept is to powerful and has so many use cases that keeping it as simple as possible is paramount.
