### ISSUE TITLE
Ddoc Lab for team workflow

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#7]
![_d](https://cloud.githubusercontent.com/assets/48370/9131092/e35839d8-3ce8-11e5-8e40-dcbab8a96905.jpg)

Ddoc Lab is more disruptive than what meets the eye, and we need  a clear vocabulary. Here are some ideas:
- we use a 2x2 cross (offline/online and production/development) to explain that _D lives in all quadrants at the same time
- _D holds "labs" in its local storage
- one lab can hold docs belonging to various sites 
- the labs are replicated to "source repos" (_D switch between them by being installed on all of them)
- design docs (and other docs) are published to "target databases"
- target databases belong to "sites" since a site or one app can use many ddocs in many Couch DBs

The "DD repo" we can save for later, because it needs an application, but if you administrated the source repos of a large no of developers well, you would never need git or github or any other centralized repo again for this kind of work.

**Comment by ermouth** [comment]
Thanks for an image – you‘ve caught an idea right. The only thing to add: you can fetch external resources to include in couchapp/ddoc – like JSON generated by CouchDB queries or github scripts or whatever.

I by myself made several sketches of workflow scheme – but not yet published, cause they all are not enough clear. Still working on it. Your two-axis dichotomy seem to be valuable, thanks.

**Comment by johs** [comment]
> On 07 Aug 2015, at 13:39, ermouth notifications@github.com wrote:
> you can fetch external resources to include in couchapp/ddoc – like JSON generated by CouchDB queries or github scripts or whatever.

This relates to ddocs, one by one..
how about the repo sync. Now I understand it as a sync on what you push in the first place.
Could there me more like a push/pul/both like in cw, and ideally filtering the db at pull by using start/end key or view?

j

**Comment by ermouth** [comment]
@johs Do not clearly understand what you mean. Can you please describe it as a scenario? Where and having what you want to start, what to do and what to achieve?

**Comment by johs** [comment]
(Related to the figure above that follow the UI of _D with source repos to the right, the one below has a conventional developer-to-production as left-to-right)
![_d-3users](https://cloud.githubusercontent.com/assets/48370/9163445/3b9f7170-3f4a-11e5-820f-79d05cc69277.png)
SCENARIO:
User A, the "builder", imports ddocs created with other tools and establish a source repo where the _D source documents are kept. Documents include data from other sources and need to be republished every time these change. 

When the builder is done, the maintenance is fairly easy and user B, the "maintainer" is doing minor changes, not only on this, but on several sites that the "builder" has set up. Therefore she/he leaves to the builder to set up all new sites, go to a given url where the _D fires up from it's source repo. User B, the maintainer, publishes most of the documents to live when they are updates, since there is a backup in daily and weekly replication to enable rollback. She/he will be switching between various labs all day, maintaining sites on demand from clients and colleagues.

User C, the "reviewer", is in charge of publishing to live sites and deals with the client and other functions and is in charge of publishing a few documents.

This starts looking like a complicated workflow, but the beauty of _D is that users can share work very flexibly and build the best workflow in a given situation.

Today, the sync from source repo to _D includes all documents with "type": "ddlab", irrespective of whether it has  "_design/" in its ID or not, right?
In setting up the sync for a specific user, instead of syncing all docs with type ddlab, would it be an idea to enable filtering for specific user roles? 
E.g. by firing up _D with a source repo url that is a view?
Additional examples to the above mentioned:
-- serve up a lab with all documents that require css maintenance to the CSS specialist.
-- serve up documents that require text review and corrections to a writer.
-- serve up documents that require fine-tuning the UI to a designer.

BENEFIT:
_D hosted in each source repo with a view per user role would allow a lab to be served that tailor and simplify the set of documents presented to each user role. Same tool, different set of documents. This would make it easy to move from one role to another, and focus on different roles by switching _D startup url,  stage.mysite.com/ddlab/role

**Comment by ermouth** [comment]
> Today, the sync from source repo to _D includes all documents with "type": "ddlab"

It syncs entire DB, no filter. But only type=="ddlab" docs are shown at the right panel.

So, from UI scope, you need auxilliary input field in sync settings popup, that, for example, can receive:
- `fieldname=value` for filtering for example type=="ddoc"
- `fieldname=/regexp/` for filtering for example _id starting with _design
- Expressions like `project=Test _id=/^(?!_design)/ owners=/[\[,]Johs[\],]/` to filter doc with .project == "Test", having _id without _design and owner containing Johs.

Also since I have never tested how filtered replication works from Pouch side, I can‘t definitely say is it possible or not. If Pouch uses remote filter function conventionally – it‘s possible.

Also I think you undestand this approach is bit unsafe in terms of access restrictions.

**Comment by johs** [comment]
For access restrictions, assume friendly environment for my use of this (in-house team).
Filtering doc list in UI (rather than DB sync) is elegant way of testing _D in team setting and for setting up various work flows through sync settings popup.
Could it be tested by tweeking this in the Ddoc Lab JSON?
  "views": {
    "info": {
      "map": "function (doc) {\n\t\t\tif (doc.type != \"ddlab\") emit (doc._id, {name:doc.name, stamp:doc.stamp, r:doc._rev});\n\t\t}"
    }
  },

How would you suggest testing an expression like project=Test _id=/^(?!_design)/ owners=/[[,]Johs[],]/ ?

**Comment by ermouth** [comment]
> How would you suggest testing

I‘ll add filter function to app ddoc. Filter functions are not like map functions – they receive request object and, so, can receive params. Even rather complex sets of params. Actually, they even can receive code.

This filter function surely gonna look like a monster, although it‘s not a problem per se – we do not have zillions of docs, so overall perfomance and RAM consumtion won‘t be a bottleneck.

**Comment by johs** [comment]
The next thing I see coming is search (like left side, but on top) since I think this editor then will be very useful to maintain datasets that have rather big document sets.

**Comment by johs** [comment]
An important quality that I am looking for in the filtering of docs for editing in _D is the ability to preconfigure _D for various roles. Access to the source repo with _D installed would require auth, while the target db normally is public. A rewrite could look like this
source.mysite.com/ddlab-name/role-name

The filter for what documents to display for editing in each role could be kept as parameter and maintained  in the main rewrite file. Or kept in separate config doc. The main point being that the user should be more or less unaware of the filtering.

**Comment by ermouth** [comment]
> The main point being that the user should be more or less unaware of the filtering

Think I have a nifty clue how to do it. 

What if every _D project had a field, where it‘s creator could explicitly enumerate all user and groups that have ability to see (and, so, edit) the project? Or leave this field blank to keep project visible for everyone?

So our filter function (that would be a part of _D) just sorts out docs that are not intended for a given user fetching db. 

So we keep _D code unaware of particular workflow scheme, although this kind of ‘ACL’ gives ability to achieve your goals. For me, this scheme is even easier to understand and need much less configuration.

Also this scheme can be upgraded to strong ACL just installing covercouch in front.

**Comment by johs** [comment]
Sounds good, especially if there is a default setting for this field that could be set up by sys adm. This would allow a certain lock-in for various roles, while giving the rest to the _D user.

**Comment by ermouth** [comment]
Implemented in Inliner standalone, closing.
