### ISSUE TITLE
Custom resource types, JSON form, markdown

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#8]
<img width="582" alt="screen shot 2015-08-11 at 05 26 41" src="https://cloud.githubusercontent.com/assets/48370/9189507/a6e0540a-3fe9-11e5-8468-8ac8a1d663a3.png">

Entering JSON manually is the general method that covers everything, but leaves no formatting across projects.
To establish input of structured JSON, would a "custom resource" type in the form of build-in forms be a possibility?
Alternatively, input in markdown or other simple and clean way to enter lists etc.?

**Comment by ermouth** [comment]
Markdown implemented and rolled out to payhip.
